assets/urls.py
from django.conf.urls import url
from .views import *

from django.views.static import *
urlpatterns = [
    url(r'jifang_add', jifang_add,name="jifang_add"),#机房
    url(r'jifang_del', jifang_del,name="jifang_del"),#机房删除
    url(r'host_add', host_add,name="host_add"),#主机添加
    url(r'host_list', host_list,name="host_list"),#主机列表
    url(r'host_edit/(\d+)', host_edit,name="host_edit"),#主机添加
    url(r'host_del/', host_del,name="host_del"),#主机删除
    url(r'command_ip', command_ip, name="command_ip"),  # 主机列表
    url(r'host_shell/',host_shell,name="host_shell"), #执行shell命令
    url(r'history/',history,name="history"), #执行shell命令
    url(r'host_info/(\d+)',host_info,name="host_info"), #主机当前信息
    url(r'text',text,name="text")




]

tommy_cmdb/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from cmdb.views import *
from .settings import *
from django.views.static import *
urlpatterns = [
    url(r'^login/', login,name="login"),#登录
    url(r'^loginout/', loginout,name="loginout"),#注销
    url(r'^admin/', admin.site.urls),
    url(r'^$', index,name="index"),#首页
    url(r'^user/', include('user.urls')),#用户管理模块
    url(r'^assets/', include('assets.urls')),#资产管理模块

    url(r'^gropus/', groups,name="groups"),#组管理
    url(r'^zhuce/', zhuce, name="zhuce"),  # 组管理
    url(r'^upload/$', upload, name="upload"),  # 组管理
url(r'^upload_db/$', upload_db, name="upload_db"),  # 组管理
url(r"^upload/(?P<path>.*)$", serve, {"document_root": MEDIA_ROOT,}),
    url(r'^webssh/', webssh, name="webssh"),  # 组管理


]

user/urls.py
from django.conf.urls import url
from .views import *

from django.views.static import *
urlpatterns = [
    url(r'^user_add/', user_add,name="user_add"),#登录
    url(r'^user_group/', user_group,name="user_group"),#用户组管理
    url(r'^user_group_del/', user_group_del,name="user_group_del"),#用户组删除
    url(r'^user_list/', user_list,name="user_list"),#用户列表
    url(r'^user_del/',user_del,name='user_del'),#删除用户
    url(r'^user_edit/(\d+)',user_edit,name='user_edit'),#删除用户
]

cmdb/models.py
from django.db import models

# Create your models here.
class Users(models.Model):
    username = models.CharField(max_length=20,verbose_name="用户名")
    password = models.CharField(max_length=20, verbose_name="密码")
    status = models.CharField(max_length=1,choices=(('0','禁用'),('1','启用')),default='1',verbose_name="用户状态")
    user_groups = models.ForeignKey("User_Groups",verbose_name="用户所属组",null=True,blank=True,on_delete=models.SET_NULL)
    create_time = models.DateTimeField(auto_now_add=True,verbose_name="创建时间")

    class Meta:
        verbose_name="用户信息"
        verbose_name_plural="用户信息"
    def __str__(self):
        return self.username

class User_Groups(models.Model):
    group_name = models.CharField(max_length=20, verbose_name="组名")
    status = models.CharField(max_length=1, choices=(('0', '禁用'), ('1', '启用')), default='1', verbose_name="组状态")
    create_time = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")
    is_super = models.CharField(max_length=1, choices=(('0', '普通用户组'), ('1', '管理组')), default='0', verbose_name="是否管理组")
    class Meta:
        verbose_name = "用户组信息"
        verbose_name_plural = "用户组信息"
    def __str__(self):
        return self.group_name
class Hosts(models.Model):
    ip = models.CharField(max_length=20, verbose_name="ip")
    password = models.CharField(max_length=30, verbose_name="密码")
    port = models.CharField(max_length=5,default='22', verbose_name="端口")
    user = models.CharField(max_length=15, verbose_name="用户")
    status = models.CharField(max_length=1, choices=(('0', '禁用'), ('1', '启用')), default='1', verbose_name="组状态")
    create_time = models.DateTimeField(auto_now_add=True,verbose_name="创建时间")
    user_groups = models.ManyToManyField("User_Groups",verbose_name="所属组",null=True,blank=True)
    jifang = models.ForeignKey("Jifang", verbose_name="所属机房",null=True,blank=True,on_delete=models.SET_NULL)
    class Meta:
        verbose_name = "主机信息"
        verbose_name_plural = "主机信息"
    def __str__(self):
        return self.ip
class Host_info(models.Model):
    os = models.TextField( verbose_name="os")
    cpu = models.TextField( verbose_name="cpu")
    disk = models.TextField( verbose_name="disk")
    mem = models.TextField( verbose_name="mem")
    network = models.TextField( verbose_name="network")
    Hosts = models.ForeignKey(Hosts)
    class Meta:
        verbose_name = "主机详细信息"
        verbose_name_plural = "主机详细信息"
    def __str__(self):
        return self.Hosts.ip


class Jifang(models.Model):
    jifang_dizhi=models.CharField(max_length=20, verbose_name="机房")
    create_time = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")
    class Meta:
        verbose_name = "机房信息"
        verbose_name_plural = "机房信息"
    def __str__(self):
        return self.jifang_dizhi
class Histry(models.Model):
    create_date=models.DateTimeField(auto_now_add=True, verbose_name="创建时间")
    histry_txt = models.CharField(max_length=100, verbose_name="执行说明")
    user = models.ForeignKey("Users",verbose_name="用户",null=True,blank=True,on_delete=models.SET_NULL)
    class Meta:
        verbose_name = "历史信息"
        verbose_name_plural = "历史信息"
    def __str__(self):
        return self.histry_txt

class Upload_db(models.Model):
    username = models.CharField(max_length=10,verbose_name="用户名")
    file = models.FileField(upload_to="./upload/%Y/%m/%d")

assets/views.py
from django.shortcuts import render,redirect,HttpResponse
from .form import *
from cmdb.models import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from tommy_cmdb.settings import *
import os,datetime,json
from .command import *
# Create your views here.

def jifang_add(request):
    """添加机房"""
    if not request.session.get("is_active", None):
        return redirect("/login/")
    user_obj = Users.objects.get(username=request.session.get("username"))
    login_user_is_super = user_obj.user_groups.is_super  # 0普通用户,1管理员
    jifang_list=Jifang.objects.all()#获取所有信息
    paginator = Paginator(jifang_list, 10)#每列10条
    page = request.GET.get('page')  # 获取用户输入的页数
    try:
        contacts = paginator.page(page)  # 获取用户输入的页来获取当页数据
    except PageNotAnInteger:
        page = 1
        contacts = paginator.page(1)  # 如果没有输入，默认第一页
    except EmptyPage:
        contacts = paginator.page(paginator.num_pages)  # 用户输入错误返回

    if request.method=="GET":
        obj = Jifang_Add_Form()
        return render(request,"assets/jifang_add.html",locals())
    elif request.method == "POST":
        obj=Jifang_Add_Form(request.POST)
        if obj.is_valid():
            jifang_name=obj.cleaned_data["jifang_name"]
            is_cunzai = Jifang.objects.filter(jifang_dizhi=jifang_name)
            #print(is_cunzai)
            if not is_cunzai:
                Jifang.objects.create(jifang_dizhi=jifang_name,create_time=datetime.datetime.now())
                user = Users.objects.get(username=request.session.get("username"))
                Histry.objects.create(user=user, create_date=datetime.datetime.now(),
                                      histry_txt=str(user.username) + "执行添加机房" + str(jifang_name) + "成功")
                return redirect("assets/jifang_add")
            else:
                add_jifang_err="机房名字存在"
                user = Users.objects.get(username=request.session.get("username"))
                Histry.objects.create(user=user, create_date=datetime.datetime.now(),
                                      histry_txt=str(user.username) + "执行添加机房" + str(jifang_name) + "失败，机房存在")
            return render(request, "assets/jifang_add.html", locals())
        else:
            return render(request,"assets/jifang_add.html",locals())

def jifang_del(request):
    """删除机房"""
    if not request.session.get("is_active", None):
        return redirect("/login/")
    req_status=""
    print(request.META['HTTP_REFERER'])
    if request.method=="POST":
        jifang_id=request.POST.get("del_id",None)
        if jifang_id:
            user = Users.objects.get(username=request.session.get("username"))
            Histry.objects.create(user=user, create_date=datetime.datetime.now(),
                                  histry_txt=str(user.username) + "执行删除机房" + str(Jifang.objects.get(pk=jifang_id).jifang_dizhi) + "成功")
            Jifang.objects.get(pk=jifang_id).delete()
            req_status = "1"
        else:
            req_status = "参数错误，联系管理员"
    else:
        req_status="未知错误，联系管理员"
    return HttpResponse(json.dumps({"req_status":req_status}),content_type="application/json")

def host_add(request):
    """添加主机"""
    if not request.session.get("is_active", None):
        return redirect("/login/")
    xinxi=""
    jifang_list = Jifang.objects.all()
    user_group_list = User_Groups.objects.all()
    if request.method=="GET":
        obj=Host_Add_Form()
        return render(request,"assets/host_add.html",locals())
    elif request.method=="POST":
        obj=Host_Add_Form(request.POST)
        if obj.is_valid():
            host_ip=obj.cleaned_data["ip"]
            host_obj=Hosts.objects.filter(ip=host_ip)
            if not host_obj:
                host_port=obj.cleaned_data["port"]
                host_user = obj.cleaned_data["user"]
                host_password = obj.cleaned_data["password"]
                host_jifang = Jifang.objects.get(pk=int(request.POST.get("jifang")))
                host_user_groups=User_Groups.objects.filter(pk__in=request.POST.getlist("user_group"))
                host_status = request.POST.get("host_status")
                create_time = datetime.datetime.now()
                host_obj=Hosts()
                host_obj.ip=host_ip
                host_obj.port=host_port
                host_obj.password=host_password
                host_obj.jifang=host_jifang
                host_obj.user=host_user
                host_obj.status=host_status
                host_obj.create_time=create_time
                host_obj.save()
                host_obj=Hosts.objects.get(ip=host_ip)
                if host_user_groups:
                    for host_user_group in host_user_groups:
                        host_obj.user_groups.add(host_user_group)
                    host_obj.save()
                xinxi="添加成功"
                user = Users.objects.get(username=request.session.get("username"))
                Histry.objects.create(user=user, create_date=datetime.datetime.now(),
                                      histry_txt=str(user.username) + "执行添加主机" + str(host_ip) + "成功")

            else :
                xinxi="主机存在，不能重复添加"

            #print(request.POST.getlist("user_group"))
            #Hosts.objects.create(ip=host_ip,port=host_port,user=host_user,password=host_password,status=host_status,create_time=create_time,user_groups=host_user_groups,jifang=host_jifang)
            return render(request, "assets/host_add.html", locals())
        else:
            return render(request, "assets/host_add.html", locals())

def host_list(request):
    if not request.session.get("is_active", None):
        return redirect("/login/")
    user_obj = Users.objects.get(username=request.session.get("username"))
    login_user_is_super = user_obj.user_groups.is_super  # 0普通用户,1管理员
    login_user_group = User_Groups.objects.get(users__username=request.session.get("username"))
    #print(login_user_group)
    host_lists = Hosts.objects.all().filter(user_groups=login_user_group)#返回普通用户组所有主机
    #print(host_lists)
    if login_user_is_super == '1':#如果是管理员组，返回所有数据
        host_lists = Hosts.objects.all()
    paginator = Paginator(host_lists, 10)  # 每列10条
    page = request.GET.get('page')  # 获取用户输入的页数
    try:
        contacts = paginator.page(page)  # 获取用户输入的页来获取当页数据
    except PageNotAnInteger:
        page = 1
        contacts = paginator.page(1)  # 如果没有输入，默认第一页
    except EmptyPage:
        contacts = paginator.page(paginator.num_pages)  # 用户输入错误返回

    #print(Hosts.objects.get(pk=7).jifang)
    if request.method=="GET":
        return render(request,"assets/host_list.html",locals())

def host_edit(request,edit_host_id):
    """修改主机"""
    if not request.session.get("is_active", None):
        return redirect("/login/")
        ###判断用户是否管理员###
    user_obj = Users.objects.get(username=request.session.get("username"))
    login_user_is_super = user_obj.user_groups.is_super  # 0普通用户,1管理员
    if login_user_is_super == "0":
        req_status = "没有权限"
        return render(request, "assets/host_edit.html", locals())
    user_group_obj=User_Groups.objects.all()
    #print (Hosts.objects.get(pk=edit_host_id).user_groups.values_list("id"))#通过主机ID获取group iD
    host_user_groups=Hosts.objects.get(pk=edit_host_id).user_groups.values_list("id")
    host_user_groups_id=[]
    for value in host_user_groups:
        #print(i[0])
        #print(value[0])
        host_user_groups_id.append(value[0])
    print(host_user_groups_id)
    req_status=""
    if request.method=="GET":
        edit_host_obj=Hosts.objects.get(pk=int(edit_host_id))
        jifang_obj = Jifang.objects.all()

        return render(request,"assets/host_edit.html",locals())
    if request.method=="POST":
        #print(request.path_info)
        port=request.POST.get("port")
        user = request.POST.get("username")
        status = request.POST.get("status")
        password = request.POST.get("password")
        jifang = Jifang.objects.get(pk=request.POST.get("jifang"))
        host_user_groups = User_Groups.objects.filter(pk__in=request.POST.getlist("user_group"))
        host_obj = Hosts.objects.get(pk=edit_host_id)
        host_obj.port=port
        host_obj.user=user
        host_obj.password=password
        host_obj.status=status
        host_obj.jifang=jifang
        host_obj.save()
        host_obj = Hosts.objects.get(pk=edit_host_id)
        #删除原来的组
        for i in host_user_groups_id:
            host_obj.user_groups.remove(User_Groups.objects.get(id=i))
        #添加新的用户组
        if host_user_groups:
            for host_user_group in host_user_groups:
                host_obj.user_groups.add(host_user_group)
            host_obj.save()

        req_status = "修改成功"
        user = Users.objects.get(username=request.session.get("username"))
        Histry.objects.create(user=user, create_date=datetime.datetime.now(),
                              histry_txt=str(user.username) + "执行修改主机" + str(host_obj.ip) + "成功")
        return redirect("/assets/host_list/")
    else:
        req_status="未知错误，联系管理员"
    return HttpResponse(json.dumps({"req_status":req_status}),content_type="application/json")

def host_del(request):
    #######删除主机##############
    if not request.session.get("is_active", None):
        return redirect("/login/")
    if request.method=="GET":
        req_status = "没有权限"
        return HttpResponse(json.dumps({"req_status": req_status}), content_type="application/json")
    elif request.method=="POST":
        id = request.POST.get("id")
        ##删除host和user组关联
        host_user_groups = Hosts.objects.get(pk=id).user_groups.values_list("id")
        host_user_groups_id = []
        host_obj=Hosts.objects.get(pk=id)
        for value in host_user_groups:
            host_obj.user_groups.remove(User_Groups.objects.get(id=value[0]))
            host_obj.save()
        user = Users.objects.get(username=request.session.get("username"))

templates/assets/command.html
<!--右侧类容-->

<pre>
    {% for i in req %}
        {% if i %}
            {{ i }}
        {% endif %}
    {% endfor %}</pre>

templates/assets/history.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}历史记录{% endblock %}

<!--首部引入javascript-->
{% block title_load_javascript %}
    <script src="{% static "bower_components/jquery/dist/jquery.min.js" %}"></script>
{% endblock %}

<!--右侧类容-->
{% block context %}
    <!--主机列表-->
    <div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header">
              <h3 class="box-title">历史记录</h3>

              <div class="box-tools">
                <div class="input-group input-group-sm" style="width: 150px;">
                  <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">

                  <div class="input-group-btn">
                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                  </div>
                </div>
              </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive no-padding">
              <table class="table table-hover">
                <tbody><tr>
                  <th>ID</th>
                  <th>用户</th>
                  <th>说明</th>
                  <th>时间</th>
                </tr>
                {% for history in contacts %}
                <tr>
                  <td>{{ history.id }}</td>
                  <td><b>{{ history.user }}</b></td>
                  <td>{{ history.histry_txt }}</td>

                  <td>
                      {{ history.create_date }}
                  </td>
                    <td></td>
                </tr>

                {% endfor %}

              </tbody></table>
            <div class="box-footer clearfix" style="padding-top: 100px;">
              <ul class="pagination pagination-sm no-margin pull-right">
                    <!--上一页-->
                   {%  if contacts.has_previous %}
                        <li><a href="{% url "history" %}?page={{ page|add:-1 }}">«</a></li>
                   {% endif %}

                  {%  if contacts.has_previous %}
                    <li><a href="{% url "history" %}?page={{ page|add:-1 }}">{{ page|add:-1 }}</a></li>
                  {% endif %}

                  <li class="active"><a href="{% url "history" %}?page={{ page }}">{{ page }}</a></li>

                  {%  if contacts.has_next %}
                    <li><a href="{% url "history" %}?page={{ page|add:1 }}">{{ page|add:1 }}</a></li>
                  {% endif %}
                    <!--下一页-->
                  {%  if contacts.has_next %}
                    <li><a href="{% url "history" %}?page={{ page|add:1 }}">»</a></li>
                  {% endif %}
              </ul>
            </div>



            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
      </div>

{% endblock %}

<!--底部引入javascript-->
{% block dibu_load_javascript %}
    <script>
        $(function () {
            //location.href = "{% url "jifang_add" %}"
        })

    </script>

{% endblock %}

templates/assets/host_edit.html
{% extends "base.html" %}

{% block title %}{{ edit_host_obj.ip }}主机修改{% endblock %}

<!--首部引入javascript-->
{% block title_load_javascript %}{% endblock %}

<!--右侧类容-->
{% block context %}
    <div class="box" style="padding-left: 30px;">
        <div class="box-header with-border">
          <h3 class="box-title">{{ edit_host_obj.ip }}主机修改</h3>
          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="" data-original-title="Collapse">
              <i class="fa fa-minus"></i></button>
            <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="" data-original-title="Remove">
              <i class="fa fa-times"></i></button>
          </div>
        </div>
        <div class="box-body" style="">
            <form action="/assets/host_edit/{{ edit_host_obj.id }}" method="post">
                {% csrf_token %}
                <table>
                    <tr style="height: 35px">
                        <th>Host ID：</th>
                        <th>
                            <input type="text" disabled="disabled" name="id" value="{{ edit_host_obj.id }}">
                        </th>
                        <th>*不可修改</th>
                    </tr>
                    <tr style="height: 35px">
                        <th>IP地址：</th>
                        <th>
                            <input type="text" disabled="disabled" name="ip" value="{{ edit_host_obj.ip }}">
                        </th>
                        <th>*不可修改</th>
                    </tr>
                    <tr style="height: 35px">
                        <th>端口：</th>
                        <th>
                            <input type="number" name="port" min="1" max="65535" required="" id="id_port" value="{{ edit_host_obj.port }}">

                        </th>
                        <th>{{ obj.ip.port.as_text }}</th>
                    </tr>
                    <tr style="height: 35px">
                        <th>ssh用户名：</th>
                        <th><input type="text"  name="username" value="{{ edit_host_obj.user }}"></th>
                        <th>{{ obj.user.errors.as_text }}</th>
                    </tr>
                    <tr style="height: 35px">
                        <th>ssh密码：</th>
                        <th><input type="password"  name="password" value="{{ edit_host_obj.password }}" maxlength="20"></th>
                        <th>{{ obj.password.errors.as_text }}</th>
                    </tr>
                    <tr style="height: 35px">
                        <th>机房选择：</th>
                        <th>
                            <select name="jifang">
                                {% for jifang in jifang_obj %}
                                    {% if edit_host_obj.jifang.id == jifang.id %}
                                        <option value="{{ jifang.id }}" selected="selected">{{ jifang.jifang_dizhi }}</option>
                                    {% else %}
                                        <option value="{{ jifang.id }}">{{ jifang.jifang_dizhi }}</option>
                                    {% endif %}
                                {% endfor %}
                            </select>
                        </th>
                        <th>{{ obj.password.errors.as_text }}</th>
                    </tr>

                    <tr style="height: 35px">
                        <th>管理用户组：</th>
                        <th>
                            <select name="user_group"  multiple="multiple" size="3">
                                {% for user_group in user_group_obj %}
                                    {% if user_group.id in host_user_groups_id  %}
                                        <option value ="{{ user_group.id }}"  selected="selected">{{ user_group.group_name }}</option>
                                    {% else %}
                                        <option value ="{{ user_group.id }}" >{{ user_group.group_name }}</option>
                                    {% endif %}
                                {% endfor %}
                            </select>
                        </th>
                        <th>*非必选项，可以多选{{ obj.password.errors.as_text }}</th>
                    </tr>
                    <tr style="height: 35px">
                        <th>禁用：</th>
                        <th>
                            {% if edit_host_obj.status == '1' %}
                                <input type="radio" name="status" checked="checked" value="1">启用 <input type="radio" name="status" value="0">禁用
                            {% else %}
                                <input type="radio" name="status" value="1">启用 <input type="radio" name="status" checked="checked" value="0">禁用
                            {% endif %}
                        </th>
                        <th>{{ obj.password.errors.as_text }}</th>
                    </tr>

                </table>

                <div class="box-footer" style="margin: 0 auto;">
                    {% if not req_status == "没有权限" %}
                        <button type="submit" class="btn btn-primary">修改主机</button>
                    {% else %}
                        <span style="color: red"><b>没有权限</b></span>
                    {% endif %}
                </div>
            </form>
        </div>
        <!-- /.box-body
        <div class="box-footer">
            <span style="color: red;">{{ xinxi }}</span>
        </div>-->
      </div>
         {% if xinxi == "主机存在，不能重复添加" %}
            <div class="callout callout-danger">
              <h4>Warning!</h4>
              <p>主机存在，不能重复添加</p>
            </div>
         {% elif xinxi == "添加成功" %}
            <div class="callout callout-info">
              <h4>Right!</h4>
              <p>添加成功</p>
            </div>
        {% endif %}

{% endblock %}

<!--底部引入javascript-->
{% block dibu_load_javascript %}{% endblock %}

templates/assets/jifang_add.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}首页{% endblock %}

<!--首部引入javascript-->
{% block title_load_javascript %}
    <script src="{% static "bower_components/jquery/dist/jquery.min.js" %}"></script>
{% endblock %}

<!--右侧类容-->
{% block context %}
    <!--添加机房-->
    {% if login_user_is_super == '1' %}
        <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">添加机房</h3>
            </div>
            <form role="form" action="{% url "jifang_add" %}" method="post">
                {% csrf_token %}
                <table style="padding-left: 10px;">
                    <tr>
                        <td>{{ obj.as_ul }}</td>
                        <td><button type="submit" class="btn btn-primary">添加机房</button></td>
                        <td style="color: red">{{ add_jifang_err }}</td>
                    </tr>
                </table>

            </form>
          </div>
    {% endif %}
    <!--机房列表-->
    <div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header">
              <h3 class="box-title">机房列表</h3>

              <div class="box-tools">
                <div class="input-group input-group-sm" style="width: 150px;">
                  <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">

                  <div class="input-group-btn">
                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                  </div>
                </div>
              </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive no-padding">
              <table class="table table-hover">
                <tbody><tr>
                  <th>ID</th>
                  <th>机房</th>
                  <th>主机</th>
                  <th>操作</th>
                </tr>
                {% for jifang in contacts %}
                <tr>
                  <td>{{ jifang.id }}</td>
                  <td>{{ jifang.jifang_dizhi }}</td>
                  <td>

                      {% for i in jifang.hosts_set.values_list  %}
                          <span style="font-size: xx-small">{{ i.1 }}&nbsp;&nbsp;</span>
                      {% endfor %}

                  </td>
                  <td>
                      {% if login_user_is_super == '1' %}
                          <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#modal-danger"  id="delete{{ jifang.id  }}">删除</button>
                      {% endif %}
                  </td>
                    <td></td>
                </tr>
                    <script>
                        $(function () {
                            $("#delete{{ jifang.id  }}").click(function(){  //当id get_msg_do点击的时候
                                var del_id={{ jifang.id }}
                                var url = '{% url "jifang_del" %}';  //设置变量URL的值
                                var data = {del_id:del_id,csrfmiddlewaretoken: '{{ csrf_token }}'};	//设置需要发送的数据
                                $.post(url,data,function(msg){  //get请求发送数据，并接受后端返回数据变量msg，msg名字可以自己定义
                                    if(msg.req_status=='1'){
                                        alert("{{ jifang.jifang_dizhi }}删除成功");
                                        //location.href = "{{ request.META.HTTP_REFERER }}"
                                        location.href = "{% url "jifang_add" %}?page={{ page }}"
                                    }
                                });
                            });
                        })

                    </script>
                {% endfor %}

              </tbody></table>
            <div class="box-footer clearfix">
              <ul class="pagination pagination-sm no-margin pull-right">
                    <!--上一页-->
                   {%  if contacts.has_previous %}
                        <li><a href="{% url "jifang_add" %}?page={{ page|add:-1 }}">«</a></li>
                   {% endif %}

                  {%  if contacts.has_previous %}
                    <li><a href="{% url "jifang_add" %}?page={{ page|add:-1 }}">{{ page|add:-1 }}</a></li>
                  {% endif %}

                  <li class="active"><a href="{% url "jifang_add" %}?page={{ page }}">{{ page }}</a></li>

                  {%  if contacts.has_next %}
                    <li><a href="{% url "jifang_add" %}?page={{ page|add:1 }}">{{ page|add:1 }}</a></li>
                  {% endif %}
                    <!--下一页-->
                  {%  if contacts.has_next %}
                    <li><a href="{% url "jifang_add" %}?page={{ page|add:1 }}">»</a></li>
                  {% endif %}
              </ul>
            </div>



            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
      </div>

{% endblock %}

<!--底部引入javascript-->
{% block dibu_load_javascript %}
    <script>
        $(function () {
            //location.href = "{% url "jifang_add" %}"
        })

    </script>

{% endblock %}