tommy_cmdb/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from cmdb.views import *
from .settings import *
from django.views.static import *
urlpatterns = [
    url(r'^login/', login,name="login"),#登录
    url(r'^loginout/', loginout,name="loginout"),#注销
    url(r'^admin/', admin.site.urls),
    url(r'^$', index,name="index"),#首页
    url(r'^user/', include('user.urls')),#用户管理模块
    url(r'^assets/', include('assets.urls')),#资产管理模块

    url(r'^gropus/', groups,name="groups"),#组管理
    url(r'^zhuce/', zhuce, name="zhuce"),  # 组管理
    url(r'^upload/$', upload, name="upload"),  # 组管理
url(r'^upload_db/$', upload_db, name="upload_db"),  # 组管理
url(r"^upload/(?P<path>.*)$", serve, {"document_root": MEDIA_ROOT,}),
    url(r'^webssh/', webssh, name="webssh"),  # 组管理


]

user/urls.py
from django.conf.urls import url
from .views import *

from django.views.static import *
urlpatterns = [
    url(r'^user_add/', user_add,name="user_add"),#登录
    url(r'^user_group/', user_group,name="user_group"),#用户组管理
    url(r'^user_group_del/', user_group_del,name="user_group_del"),#用户组删除
    url(r'^user_list/', user_list,name="user_list"),#用户列表
    url(r'^user_del/',user_del,name='user_del'),#删除用户
    url(r'^user_edit/(\d+)',user_edit,name='user_edit'),#删除用户
]

cmdb/models.py
from django.db import models

# Create your models here.
class Users(models.Model):
    username = models.CharField(max_length=20,verbose_name="用户名")
    password = models.CharField(max_length=20, verbose_name="密码")
    status = models.CharField(max_length=1,choices=(('0','禁用'),('1','启用')),default='1',verbose_name="用户状态")
    user_groups = models.ForeignKey("User_Groups",verbose_name="用户所属组",null=True,blank=True,on_delete=models.SET_NULL)
    create_time = models.DateTimeField(auto_now_add=True,verbose_name="创建时间")

    class Meta:
        verbose_name="用户信息"
        verbose_name_plural="用户信息"
    def __str__(self):
        return self.username

class User_Groups(models.Model):
    group_name = models.CharField(max_length=20, verbose_name="组名")
    status = models.CharField(max_length=1, choices=(('0', '禁用'), ('1', '启用')), default='1', verbose_name="组状态")
    create_time = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")
    is_super = models.CharField(max_length=1, choices=(('0', '普通用户组'), ('1', '管理组')), default='0', verbose_name="是否管理组")
    class Meta:
        verbose_name = "用户组信息"
        verbose_name_plural = "用户组信息"
    def __str__(self):
        return self.group_name
class Hosts(models.Model):
    ip = models.CharField(max_length=20, verbose_name="ip")
    password = models.CharField(max_length=30, verbose_name="密码")
    port = models.CharField(max_length=5,default='22', verbose_name="端口")
    user = models.CharField(max_length=15, verbose_name="用户")
    status = models.CharField(max_length=1, choices=(('0', '禁用'), ('1', '启用')), default='1', verbose_name="组状态")
    create_time = models.DateTimeField(auto_now_add=True,verbose_name="创建时间")
    user_groups = models.ManyToManyField("User_Groups",verbose_name="所属组",null=True,blank=True)
    jifang = models.ForeignKey("Jifang", verbose_name="所属机房",null=True,blank=True,on_delete=models.SET_NULL)
    class Meta:
        verbose_name = "主机信息"
        verbose_name_plural = "主机信息"
    def __str__(self):
        return self.ip
class Host_info(models.Model):
    os = models.TextField( verbose_name="os")
    cpu = models.TextField( verbose_name="cpu")
    disk = models.TextField( verbose_name="disk")
    mem = models.TextField( verbose_name="mem")
    network = models.TextField( verbose_name="network")
    Hosts = models.ForeignKey(Hosts)
    class Meta:
        verbose_name = "主机详细信息"
        verbose_name_plural = "主机详细信息"
    def __str__(self):
        return self.Hosts.ip


class Jifang(models.Model):
    jifang_dizhi=models.CharField(max_length=20, verbose_name="机房")
    create_time = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")
    class Meta:
        verbose_name = "机房信息"
        verbose_name_plural = "机房信息"
    def __str__(self):
        return self.jifang_dizhi
class Histry(models.Model):
    create_date=models.DateTimeField(auto_now_add=True, verbose_name="创建时间")
    histry_txt = models.CharField(max_length=100, verbose_name="执行说明")
    user = models.ForeignKey("Users",verbose_name="用户",null=True,blank=True,on_delete=models.SET_NULL)
    class Meta:
        verbose_name = "历史信息"
        verbose_name_plural = "历史信息"
    def __str__(self):
        return self.histry_txt

class Upload_db(models.Model):
    username = models.CharField(max_length=10,verbose_name="用户名")
    file = models.FileField(upload_to="./upload/%Y/%m/%d")

user/views.py
from django.shortcuts import render,redirect,HttpResponse
from .form import *
from cmdb.models import *
from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage
from tommy_cmdb.settings import *
import os,datetime,json
# Create your views here.
def user_add(request):
    """添加用户"""
    if not request.session.get("is_active",None):
        return redirect("/login/")
    ###判断用户是否管理员###
    user_obj = Users.objects.get(username=request.session.get("username"))
    login_user_is_super = user_obj.user_groups.is_super  # 0普通用户,1管理员

    user_group_obj=User_Groups.objects.all()
    xinxi=""
    if request.method == "GET":
        obj = User_Add_Form()
        return render(request,"user/user_add.html",locals())
    elif request.method=="POST":
        obj = User_Add_Form(request.POST)
        if obj.is_valid():
            username = obj.cleaned_data["username"]
            password = obj.cleaned_data["password"]
            status = request.POST.get("status")
            groups = User_Groups.objects.get(pk=request.POST.get("groups"))
            create_time=datetime.datetime.now()
            if not Users.objects.filter(username=username):
                Users.objects.create(username=username,password=password,status=status,user_groups=groups,create_time=create_time)
                xinxi="添加成功"
                user=Users.objects.get(username=request.session.get("username"))
                Histry.objects.create(user=user, create_date=datetime.datetime.now(),
                                      histry_txt=str(user.username) + "执行添加用户" + str(username) + "成功")
            else:
                xinxi="用户存在"
                user = Users.objects.get(username=request.session.get("username"))
                Histry.objects.create(user=user, create_date=datetime.datetime.now(),
                                      histry_txt=str(user.username) + "执行添加用户" + str(username) + "失败，用户存在")
            return render(request, "user/user_add.html", locals())
        else:
            return render(request, "user/user_add.html", locals())

def user_list(request):
    if not request.session.get("is_active",None):
        return redirect("/login/")
        ###判断用户是否管理员###
    user_obj = Users.objects.get(username=request.session.get("username"))
    login_user_is_super = user_obj.user_groups.is_super  # 0普通用户,1管理员

    user_list_obj=Users.objects.all()
    paginator = Paginator(user_list_obj, 10)  # 每列10条
    page = request.GET.get('page')  # 获取用户输入的页数
    try:
        contacts = paginator.page(page)  # 获取用户输入的页来获取当页数据
    except PageNotAnInteger:
        page = 1
        contacts = paginator.page(1)  # 如果没有输入，默认第一页
    except EmptyPage:
        contacts = paginator.page(paginator.num_pages)  # 用户输入错误返回

    if request.method == "GET":
        return render(request,"user/user_list.html",locals())

def user_del(request):
    """删除用户"""
    if not request.session.get("is_active", None):
        return redirect("/login/")
    req_status=""
    #print(request.META['HTTP_REFERER'])
    if request.method=="POST":
        user_group_id=request.POST.get("del_id",None)
        if user_group_id:
            user = Users.objects.get(username=request.session.get("username"))
            Histry.objects.create(user=user, create_date=datetime.datetime.now(),
                                  histry_txt=str(user.username) + "执行删除用户组" + str(
                                      Users.objects.get(pk=user_group_id).username) + "成功")

            Users.objects.get(pk=user_group_id).delete()
            req_status = "1"
        else:
            req_status = "参数错误，联系管理员"
    else:
        req_status="未知错误，联系管理员"
    return HttpResponse(json.dumps({"req_status":req_status}),content_type="application/json")

def user_edit(request,edit_user_id):
    """修改用户"""
    if not request.session.get("is_active", None):
        return redirect("/login/")
        ###判断用户是否管理员###
    user_obj = Users.objects.get(username=request.session.get("username"))
    login_user_is_super = user_obj.user_groups.is_super  # 0普通用户,1管理员
    if login_user_is_super == "0":
        req_status = "没有权限"
        return render(request, "user/user_edit.html", locals())
    user_group_obj=User_Groups.objects.all()

    req_status=""
    if request.method=="GET":
        edit_user_obj=Users.objects.get(pk=int(edit_user_id))
        return render(request,"user/user_edit.html",locals())
    if request.method=="POST":
        #print(request.path_info)
        password=request.POST.get("password",None)
        status = request.POST.get("status")
        edit_user_group = User_Groups.objects.get(pk=request.POST.get("groups"))
        user_obj = Users.objects.get(pk=edit_user_id)
        user_obj.password=password
        user_obj.status=status
        user_obj.user_groups=edit_user_group
        user_obj.save()
        req_status = "修改成功"
        user = Users.objects.get(username=request.session.get("username"))
        Histry.objects.create(user=user, create_date=datetime.datetime.now(),
                              histry_txt=str(user.username) + "执行修改用户" + str(user_obj.username) + "成功")
        return redirect("/user/user_list/")
    else:
        req_status="未知错误，联系管理员"
    return HttpResponse(json.dumps({"req_status":req_status}),content_type="application/json")

def user_group(request):
    if not request.session.get("is_active",None):
            return redirect("/login/")
    user_obj = Users.objects.get(username=request.session.get("username"))
    login_user_is_super = user_obj.user_groups.is_super  # 0普通用户,1管理员

    user_group_obj=User_Groups.objects.all()
    paginator = Paginator(user_group_obj, 10)  # 每列10条
    page = request.GET.get('page')  # 获取用户输入的页数
    try:
        contacts = paginator.page(page)  # 获取用户输入的页来获取当页数据
    except PageNotAnInteger:
        page = 1
        contacts = paginator.page(1)  # 如果没有输入，默认第一页
    except EmptyPage:
        contacts = paginator.page(paginator.num_pages)  # 用户输入错误返回



    if request.method == "GET":
        obj=User_Group_Form()
        return render(request,"user/user_group.html",locals())
    if request.method == "POST":
        obj = User_Group_Form(request.POST)
        if obj.is_valid():
            group_name=obj.cleaned_data["group_name"]
            is_super = request.POST.get("is_super")
            create_time = datetime.datetime.now()
            group_obj = User_Groups.objects.filter(group_name=group_name)
            if not group_obj:
                User_Groups.objects.create(group_name=group_name,is_super=is_super,create_time=create_time)
                return redirect("user/user_group/")
            else:
                add_group_err = "用户组存在"
            return render(request, "user/user_group.html", locals())
        else:
            return render(request, "user/user_group.html", locals())


def user_group_del(request):
    """删除用户组"""
    if not request.session.get("is_active", None):
        return redirect("/login/")
    req_status=""
    #print(request.META['HTTP_REFERER'])
    if request.method=="POST":
        user_group_id=request.POST.get("del_id",None)
        if user_group_id:
            user = Users.objects.get(username=request.session.get("username"))
            Histry.objects.create(user=user, create_date=datetime.datetime.now(),
                                  histry_txt=str(user.username) + "执行删除用户组" + str(User_Groups.objects.get(pk=user_group_id).group_name) + "成功")
            User_Groups.objects.get(pk=user_group_id).delete()
            req_status = "1"

        else:
            req_status = "参数错误，联系管理员"
    else:
        req_status="未知错误，联系管理员"
    return HttpResponse(json.dumps({"req_status":req_status}),content_type="application/json")
    User_Groups.objects.get(pk=user_group_id).hosts_set

templates/user/indexbak.html
{% extends "base.html" %}

{% block title %}首页{% endblock %}

<!--首部引入javascript-->
{% block title_load_javascript %}{% endblock %}

<!--右侧类容-->
{% block context %}
    <center>我是首页</center>
{% endblock %}

<!--底部引入javascript-->
{% block dibu_load_javascript %}{% endblock %}

templates/user/user.html
{% extends "base.html" %}

{% block title %}首页{% endblock %}

<!--首部引入javascript-->
{% block title_load_javascript %}{% endblock %}

<!--右侧类容-->
{% block context %}
    <div style="padding-left: 30px;padding-top: 10px;padding-right: 10px;">
<button type="button" class="btn btn-block btn-success" style="width: 15%">添加主机</button>
</div>
    <div class="row" style="padding-top: 10px;">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header">
              <h3 class="box-title">Responsive Hover Table</h3>

              <div class="box-tools">
                <div class="input-group input-group-sm" style="width: 150px;">
                  <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">

                  <div class="input-group-btn">
                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                  </div>
                </div>
              </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive no-padding">
              <table class="table table-hover">
                <tbody><tr>
                  <th>ID</th>
                  <th>User</th>
                  <th>Date</th>
                  <th>Status</th>
                  <th>Reason</th>
                </tr>
                <tr>
                  <td>183</td>
                  <td>John Doe</td>
                  <td>11-7-2014</td>
                  <td><span class="label label-success">Approved</span></td>
                  <td>Bacon ipsum dolor sit amet salami venison chicken flank fatback doner.</td>
                </tr>
                <tr>
                  <td>219</td>
                  <td>Alexander Pierce</td>
                  <td>11-7-2014</td>
                  <td><span class="label label-warning">Pending</span></td>
                  <td>Bacon ipsum dolor sit amet salami venison chicken flank fatback doner.</td>
                </tr>
                <tr>
                  <td>657</td>
                  <td>Bob Doe</td>
                  <td>11-7-2014</td>
                  <td><span class="label label-primary">Approved</span></td>
                  <td>Bacon ipsum dolor sit amet salami venison chicken flank fatback doner.</td>
                </tr>
                <tr>
                  <td>175</td>
                  <td>Mike Doe</td>
                  <td>11-7-2014</td>
                  <td><span class="label label-danger">Denied</span></td>
                  <td>Bacon ipsum dolor sit amet salami venison chicken flank fatback doner.</td>
                </tr>
              </tbody></table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
      </div>

{% endblock %}

<!--底部引入javascript-->
{% block dibu_load_javascript %}{% endblock %}

templates/user/user_add.html
{% extends "base.html" %}

{% block title %}添加用户{% endblock %}

<!--首部引入javascript-->
{% block title_load_javascript %}{% endblock %}

<!--右侧类容-->
{% block context %}

    <div class="box" style="padding-left: 30px;">
        <div class="box-header with-border">
          <h3 class="box-title">添加用户</h3>
          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="" data-original-title="Collapse">
              <i class="fa fa-minus"></i></button>
            <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="" data-original-title="Remove">
              <i class="fa fa-times"></i></button>
          </div>
        </div>
        <div class="box-body" style="">
            <form action="{% url "user_add" %}" method="post">
                {% csrf_token %}
                <table>
                    <tr style="height: 35px">
                        <th>用户名：</th>
                        <th>{{ obj.username }}</th>
                        <th>{{ obj.username.errors.as_text }}</th>
                    </tr>
                    <tr style="height: 35px">
                        <th>密码：</th>
                        <th>{{ obj.password }}</th>
                        <th>{{ obj.password.port.as_text }}</th>
                    </tr>
                    <tr style="height: 35px">
                        <th>用户组：</th>
                        <th>
                            <select name="groups">
                                {% for group in user_group_obj %}
                                    <option value ="{{ group.id }}">{{ group.group_name }}</option>
                                {% endfor %}
                            </select>
                        </th>
                        <th>{{ obj.password.errors.as_text }}</th>
                    </tr>

                    <tr style="height: 35px">
                        <th>禁用：</th>
                        <th><input type="radio" name="status" checked="checked" value="1">启用 <input type="radio" name="status" value="0">禁用</th>
                        <th>{{ obj.password.errors.as_text }}</th>
                    </tr>

                </table>

                <div class="box-footer" style="margin: 0 auto;">
                    {% if not user_group_obj %}
                        <span style="color: red">需要先添加机房才能显示添加主机按钮</span>
                    {% elif login_user_is_super == "0" %}
                        <span style="color: red">权限拒绝，只能管理员组能操作</span>
                    {% else %}
                        <button type="submit" class="btn btn-primary">添加用户</button>

                    {% endif %}

                </div>
            </form>
        </div>
        <!-- /.box-body
        <div class="box-footer">
            <span style="color: red;">{{ xinxi }}</span>
        </div>-->
      </div>

         {% if xinxi == "用户存在" %}
            <div class="callout callout-danger">
              <h4>Warning!</h4>
              <p>用户存在，不能重复添加</p>
            </div>
         {% elif xinxi == "添加成功" %}
            <div class="callout callout-info">
              <h4>Right!</h4>
              <p>添加成功</p>
            </div>
        {% endif %}

{% endblock %}

<!--底部引入javascript-->
{% block dibu_load_javascript %}{% endblock %}

templates/user/user_edit.html
{% extends "base.html" %}

{% block title %}修改用户{% endblock %}

<!--首部引入javascript-->
{% block title_load_javascript %}{% endblock %}

<!--右侧类容-->
{% block context %}

    <div class="box" style="padding-left: 30px;">
        <div class="box-header with-border">
          <h3 class="box-title">修改用户</h3>
          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="" data-original-title="Collapse">
              <i class="fa fa-minus"></i></button>
            <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="" data-original-title="Remove">
              <i class="fa fa-times"></i></button>
          </div>
        </div>
        <div class="box-body" style="">
            <form action="/user/user_edit/{{ edit_user_obj.id }}" method="post">

                {% csrf_token %}
                <table>
                    <tr style="height: 35px">
                        <th>UID：</th>
                        <th><input type="text" name="id" value="{{ edit_user_obj.id }}" disabled="disabled"></th>
                        <th></th>
                    </tr>
                    <tr style="height: 35px">
                        <th>用户名：</th>
                        <th><input type="text" name="username" value="{{ edit_user_obj.username }}" disabled="disabled"></th>
                        <th></th>
                    </tr>
                    <tr style="height: 35px">
                        <th>密码：</th>
                        <th><input type="password" name="password" value="{{ edit_user_obj.password }}"  maxlength="20"></th>
                        <th></th>
                    </tr>
                    <tr style="height: 35px">
                        <th>用户组：</th>
                        <th>
                            <select name="groups">
                            <!--判断自动是当前组-->
                                {% for group in user_group_obj %}
                                    {% if edit_user_obj.user_groups.id == group.id %}
                                        <option value="{{ group.id }}" selected="selected">{{ group.group_name }}</option>
                                    {% else %}
                                        <option value="{{ group.id }}">{{ group.group_name }}</option>
                                    {% endif %}
                                {% endfor %}
                            </select>
                        </th>
                        <th></th>
                    </tr>

                    <tr style="height: 35px">
                        <th>禁用：</th>
                        <th>
                            {% if edit_user_obj.status == '1' %}
                                <input type="radio" name="status" checked="checked" value="1">启用 <input type="radio" name="status" value="0">禁用
                            {% else %}
                                <input type="radio" name="status" value="1">启用 <input type="radio" name="status" checked="checked" value="0">禁用
                            {% endif %}
                        </th>
                        <th></th>
                    </tr>

                </table>

                <div class="box-footer" style="margin: 0 auto;">
                    {% if not req_status == "没有权限" %}
                        <button type="submit" class="btn btn-primary">修改用户</button>
                        {% else %}
                        <span style="color: red"><b>没有权限</b></span>
                    {% endif %}



                </div>
            </form>
        </div>
        <!-- /.box-body
        <div class="box-footer">
            <span style="color: red;">{{ xinxi }}</span>
        </div>-->
      </div>

         {% if xinxi == "用户存在" %}
            <div class="callout callout-danger">
              <h4>Warning!</h4>
              <p>用户存在，不能重复添加</p>
            </div>
         {% elif xinxi == "修改成功" %}
            <div class="callout callout-info">
              <h4>Right!</h4>
              <p>修改成功</p>
            </div>
        {% endif %}

{% endblock %}

<!--底部引入javascript-->
{% block dibu_load_javascript %}{% endblock %}

templates/user/user_group.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}用户组管理{% endblock %}

<!--首部引入javascript-->
{% block title_load_javascript %}
    <script src="{% static "bower_components/jquery/dist/jquery.min.js" %}"></script>
{% endblock %}

<!--右侧类容-->
{% block context %}
    <!--添加用户组-->
    {% if login_user_is_super == '1' %}
        <div class="box box-primary" style="padding-left: 10px;">
            <div class="box-header with-border">
              <h3 class="box-title">添加用户组</h3>
            </div>
            <form role="form" action="{% url "user_group" %}" method="post">
                {% csrf_token %}
                <table style="padding-left: 30px;">
                    <tr style="height: 30px;">
                        <th>组名：</th>
                        <td>{{ obj.group_name }}</td>
                        <td style="color: red">{{ add_group_err }}</td>
                    </tr>
                    <tr style="height: 30px;">
                        <th>管理组：</th>
                        <td>
                            <input type="radio" name="is_super" value="0" checked="checked">否
                            <input type="radio" name="is_super" value="1">是
                        </td>
                        <td style="color: red"></td>
                    </tr>
                    <tr style="height: 30px;">
                        <th></th>
                        <td>
                            <button type="submit" class="btn btn-primary">添加用户组</button>
                        </td>
                        <td style="color: red"></td>
                    </tr>


                </table>

            </form>
          </div>
    {% endif %}
    <!--用户组列表-->
    <div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header">
              <h3 class="box-title">用户组列表</h3>

              <div class="box-tools">
                <div class="input-group input-group-sm" style="width: 150px;">
                  <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">

                  <div class="input-group-btn">
                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                  </div>
                </div>
              </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive no-padding">
              <table class="table table-hover">
                <tbody>
                <tr>
                  <th>ID</th>
                  <th>用户组名字</th>
                  <th>管理员组</th>
                  <th>组用户</th>
                  <th>管理主机</th>
                  <th>操作</th>
                </tr>
                {% for user_group in contacts %}
                <tr>
                  <td>{{ user_group.id }}</td>
                  <td>{{ user_group.group_name }}</td>
                  <td>
                      {% if user_group.is_super == "1"  %}
                          <span class="label label-success">管理组</span>
                      {% else %}
                          <span class="label label-warning">普通用户组</span>
                      {% endif %}
                  </td>
                  <td>
                      {% for i in user_group.users_set.values %}
                          {{ i.username }}&nbsp;&nbsp;
                      {% endfor %}

                  </td>
                  <td>
                      {% for i in user_group.hosts_set.values %}
                          {{ i.ip }}&nbsp;&nbsp;
                      {% endfor %}
                  </td>
                  <td>
                      {% if login_user_is_super == '1' %}
                          <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#modal-danger"  id="delete{{ user_group.id  }}">删除</button>
                      {% endif %}
                  </td>
                    <td></td>
                </tr>
                    <script>
                        $(function () {
                            $("#delete{{ user_group.id  }}").click(function(){  //当id get_msg_do点击的时候
                                var del_id={{ user_group.id }}
                                var url = '{% url "user_group_del" %}';  //设置变量URL的值
                                var data = {del_id:del_id,csrfmiddlewaretoken: '{{ csrf_token }}'};	//设置需要发送的数据
                                $.post(url,data,function(msg){  //get请求发送数据，并接受后端返回数据变量msg，msg名字可以自己定义
                                    if(msg.req_status=='1'){
                                        alert("{{ user_group.group_name }}删除成功");
                                        //location.href = "{{ request.META.HTTP_REFERER }}"
                                        location.href = "{% url "user_group" %}?page={{ page }}"
                                    }
                                });
                            });
                        })

                    </script>
                {% endfor %}

              </tbody></table>
            <div class="box-footer clearfix">
              <ul class="pagination pagination-sm no-margin pull-right">
                    <!--上一页-->
                   {%  if contacts.has_previous %}
                        <li><a href="{% url "user_group" %}?page={{ page|add:-1 }}">«</a></li>
                   {% endif %}

                  {%  if contacts.has_previous %}
                    <li><a href="{% url "user_group" %}?page={{ page|add:-1 }}">{{ page|add:-1 }}</a></li>
                  {% endif %}

                  <li class="active"><a href="{% url "user_group" %}?page={{ page }}">{{ page }}</a></li>

                  {%  if contacts.has_next %}
                    <li><a href="{% url "user_group" %}?page={{ page|add:1 }}">{{ page|add:1 }}</a></li>
                  {% endif %}
                    <!--下一页-->
                  {%  if contacts.has_next %}
                    <li><a href="{% url "user_group" %}?page={{ page|add:1 }}">»</a></li>
                  {% endif %}
              </ul>
            </div>



            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
      </div>

{% endblock %}

<!--底部引入javascript-->
{% block dibu_load_javascript %}
    <script>
        $(function () {
            //location.href = "{% url "jifang_add" %}"
        })

    </script>

{% endblock %}